### ISSUE TITLE
module eventEmmiter not found

### ISSUE THREAD

**Issue by janwillemtulp** [nl253/GeneticAlgo-JS#1]
running genetic-algo-2.0.0.alpha.5 (and node 12.2.0) I get the following error when I just import the GA module:

```
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module './eventEmitter'
Require stack:
- /Users/janwillemtulp/repo/genetic/node_modules/genetic-algo/index.js
- /Users/janwillemtulp/repo/genetic/tasks/test.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /Users/janwillemtulp/repo/heineken-career-map/node_modules/genetic-algo/index.js:78:26
    at /Users/janwillemtulp/repo/heineken-career-map/node_modules/genetic-algo/index.js:69:17
    at Object.<anonymous> (/Users/janwillemtulp/repo/heineken-career-map/node_modules/genetic-algo/index.js:75:3)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
```

**Comment by nl253** [comment]
Thanks for raising the issue. I think it should be fixed now. Try using the newest version: `genetic-algo@2.0.0-alpha.7`.
